
name: 00-Setup-Create-Docs-And-Docs-QA-Repos
on: 
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Create -docs repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs"
          TEMPLATE="https://github.com/ucsb-cs156-w22/TEMPLATE-docs"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}  
          DESC="Documentation for ${OWNER_PLUS_REPOSITORY}"      
          echo "If you get the error: "
          echo "      To authenticate, please run \'gh auth login\'"
          echo "Then: you need to set the actions secret \`DOCS_TOKEN\` to a personal access token"
          echo "      that has repo scope".
          echo ""
          echo "About to run command:"
          echo " gh repo create ${NEW_REPO} --public --description \"${DESC}\" --template ${TEMPLATE} "
          gh repo create ${NEW_REPO} --public --description "${DESC}" --template ${TEMPLATE}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
      - name: "Set homepage in -docs repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}
          echo "About to run command:"
          echo " gh repo edit ${NEW_REPO} --homepage ${HOMEPAGE}"
          gh repo edit ${NEW_REPO} --homepage ${HOMEPAGE}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
      - name: "Enable GitHub pages on -docs repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}
          GITHUB_PAGES_JSON='{"source":{"branch":"main","path":"/docs"}}'
          echo "curl -X POST -H 'Accept: application/vnd.github.v3+json' -H 'authorization: Bearer ${{secrets.DOCS_TOKEN}}'  https://api.github.com/repos/${OWNER_PLUS_REPOSITORY}${SUFFIX}/pages -d ${GITHUB_PAGES_JSON}"
          curl -X POST -H 'Accept: application/vnd.github.v3+json' -H 'authorization: Bearer ${{secrets.DOCS_TOKEN}}'  https://api.github.com/repos/${OWNER_PLUS_REPOSITORY}${SUFFIX}/pages -d ${GITHUB_PAGES_JSON}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}    
      - name: "Create -docs-qa repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs-qa"
          TEMPLATE="https://github.com/ucsb-cs156-w22/TEMPLATE-docs"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}  
          DESC="Documentation QA site for ${OWNER_PLUS_REPOSITORY}"
          echo "About to run command:"
          echo " gh repo create ${NEW_REPO} --public --description \"${DESC}\" --template ${TEMPLATE} "
          gh repo create ${NEW_REPO} --public --description "${DESC}" --template ${TEMPLATE}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
      - name: "Set homepage in -docs repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs-qa"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}
          echo "About to run command:"
          echo " gh repo edit ${NEW_REPO} --homepage ${HOMEPAGE}"
          gh repo edit ${NEW_REPO} --homepage ${HOMEPAGE}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
      - name: "Enable GitHub pages on -docs-qa repo"
        working-directory: .
        continue-on-error: true
        run: |
          SUFFIX="-docs-qa"
          OWNER_PLUS_REPOSITORY=${{github.repository}}
          OWNER=${{ github.repository_owner }}
          REPOSITORY=${OWNER_PLUS_REPOSITORY/$OWNER\//}
          HOMEPAGE="https://${OWNER}.github.io/${REPOSITORY}${SUFFIX}"
          NEW_REPO=${OWNER_PLUS_REPOSITORY}${SUFFIX}
          GITHUB_PAGES_JSON='{"source":{"branch":"main","path":"/docs"}}'
          echo "curl -X POST -H 'Accept: application/vnd.github.v3+json' -H 'authorization: Bearer ${{secrets.DOCS_TOKEN}}'  https://api.github.com/repos/${OWNER_PLUS_REPOSITORY}${SUFFIX}/pages -d ${GITHUB_PAGES_JSON}"
          curl -X POST -H 'Accept: application/vnd.github.v3+json' -H 'authorization: Bearer ${{secrets.DOCS_TOKEN}}'  https://api.github.com/repos/${OWNER_PLUS_REPOSITORY}${SUFFIX}/pages -d ${GITHUB_PAGES_JSON}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}    



   